# Generated by Django 3.2.16 on 2023-08-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(max_length=32)),
                ('title_en', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'club_types',
            },
        ),
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(max_length=32)),
                ('title_en', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'event_series',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(max_length=32)),
                ('title_en', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'event_types',
            },
        ),
    ]
