# Generated by Django 3.2.16 on 2023-08-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=64, unique=True)),
                ('name_en', models.CharField(max_length=64, unique=True)),
                ('url_id', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_publicly_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.community')),
                ('location', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('A', 'Approved'), ('C', 'Cancelled')], default='W', max_length=1)),
                ('event_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.eventseries')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.eventtype')),
            ],
            bases=('community.community',),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.community')),
                ('room', models.CharField(blank=True, max_length=16, null=True)),
                ('founded_date', models.DateField()),
                ('tags', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('R', 'Recruiting'), ('C', 'Closed'), ('D', 'Disbanded')], default='R', max_length=1)),
            ],
            bases=('community.community',),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.community')),
                ('room', models.CharField(blank=True, max_length=32, null=True)),
                ('founded_date', models.DateField()),
                ('is_official', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('R', 'Recruiting'), ('C', 'Closed'), ('D', 'Disbanded')], default='R', max_length=1)),
                ('club_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.clubtype')),
            ],
            bases=('community.community',),
        ),
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.event')),
                ('allows_outside_participators', models.BooleanField(default=False)),
                ('created_under', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.community')),
            ],
            bases=('community.event',),
        ),
    ]
